Models/Investimento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JurosReal.Models
{
    public class Investimento :TaxaView
    {
       [DataType(DataType.Currency)]
       public double ValorInvestido { get; set; }

       public double Meses { get; set; }
       [DataType(DataType.Currency)]
       public double RetornoBruto { get; set; }
       [DataType(DataType.Currency)]
       public double RetornoLiquido { get; set; }
       [DataType(DataType.Currency)]
       public double RetornoReal { get; set; }
       [DataType(DataType.Currency)]
       public double Rentabilidade { get; set; }

       public double Ir { get; set; }
    }
}

Models/TaxaDeJuros.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;


namespace JurosReal.Models
{
    public class TaxaDeJuros
    {   
        [JsonPropertyName("nome")]
        public string Nome { get; set; }

        [JsonPropertyName("valor")]
        public double Valor { get; set; }
        
    }
}

Models/TaxaView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace JurosReal.Models
{
    public class TaxaView
    {
        [JsonPropertyName("nome")]
        public string NomeTaxa { get; set; }

        [JsonPropertyName("valor")]
        public double Valor { get; set; }
    }
}

Controllers/TaxaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using JurosReal.Models;


namespace JurosReal.Controllers
{
    public class TaxaController : Controller
    {
        public IActionResult Index( )
             {
               return View();
             }
        
        public async Task<ActionResult> Calcular(Investimento investe )
        {
            
            using HttpClient client = new()
            {
                BaseAddress = new Uri("https://brasilapi.com.br/api/taxas/v1/{sigla}")
            };
            // Get the user information.
            TaxaView? taxa = await client.GetFromJsonAsync<TaxaView>($"{investe.NomeTaxa}");
            var taxaIpca = await client.GetFromJsonAsync<TaxaView>("IPCA");

            if(investe.Meses <= 6)
            {
            investe.Ir = 0.775;
             
            } 
             else if (investe.Meses <= 12)
            {
                investe.Ir = 0.80;

            }
             else if (investe.Meses <= 24)
            {
                investe.Ir = 0.825;
            }
             else
            {
                investe.Ir = 0.85;
            }
            
            investe.Rentabilidade =((((taxa.Valor/100)/12)*investe.Meses) * investe.ValorInvestido);
            investe.RetornoBruto =   investe.Rentabilidade + investe.ValorInvestido;
            investe.RetornoLiquido = investe.Rentabilidade * investe.Ir + investe.ValorInvestido;
            investe.RetornoReal = investe.RetornoLiquido -(((taxaIpca.Valor/100)/12)*investe.Meses);
            
            return View(investe);
                 
        }
 
    }    
    
    }

    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JurosReal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JurosReal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JurosReal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Taxa" asp-action="Index">Calculadora</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  href="https://vlgonzalez.github.io/cv/#principa">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  href="https://vlgonzalez.github.io/cv/projetos.html">Projetos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - JurosReal - Create by Vlgonzalez <a href="https://github.com/vlgonzalez">GitHub</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Taxa/Buscar.cshtml
@using System.Data
@model JurosReal.Models.Investimento

@{
    ViewData["Title"] ="Retorno";
}
<body>
    

<h2>Retorno do investimento</h2>
<p>Valor aplicado =  @Html.DisplayFor(model => model.ValorInvestido)</p>
<p>Valor do Retorno bruto =  @Html.DisplayFor(model => model.RetornoBruto)</p>
<p>Valor do Retorno liquido =  @Html.DisplayFor(model => model.RetornoLiquido)</p>
<p>Valor do Retorno real =  @Html.DisplayFor(model => model.RetornoReal)</p>

<h2>Definições </h2>
<p>Inflação: é um aumento geral nos preços de bens e serviços em uma economia.Resumindo, sabe aquele churrasco que ano passado você fazia com R$100,00, e hoje faz com R$120,00, esse aumento de preços é a inflação, que com a mesma quantidade de dinheiro de um período passado você consegue comprar menos. </p>
<p>Retorno bruto: Valor do seus investimentos antes do desconto imposto de renda retido na fonte no momento do resgate da sua aplicação</p>
<p>Retorno Liquido: Valor dos seus investimentos após o resgate e desconto do imposto de renda sobre o seu lucro.
Lembrando que o IR é regressivo, ou seja quanto mais tempo você deixar o seu dinheiro aplicado menos imposto ira pagar, e maior será o seu lucro. . </p>
<p>Até 180 dias (6 meses) = IR de 22,5% sobre o lucro</p>
<p>Até 181 dias até 360 dias (12 meses) = IR de 20,0% sobre o lucro</p>
<p>Até 361 dias até 720 dias (24 meses) = IR de 17,5% sobre o lucro</p>
<p>Acima de 720 dias (mais de 24 meses) = IR de 15,0% sobre o lucro</p>
<p>Retorno real: Valor liquido do seu investimento descontando a inflação do período da sua aplicação.Ou seja já descontado a desvalorização do seu dinheiro durante  </p>

 </body>   

Views/Taxa/Calcular.cshtml
@using System.Data
@model JurosReal.Models.Investimento

@{
    ViewData["Title"] ="Retorno";
}
<body>
    

<h2>Retorno do investimento</h2>
<p>Valor aplicado = R @Html.DisplayFor(model => model.ValorInvestido)</p>
<p>Valor do Retorno bruto = R @Html.DisplayFor(model => model.RetornoBruto)</p>
<p>Valor do Retorno liquido = R @Html.DisplayFor(model => model.RetornoLiquido)</p>
<p>Valor do Retorno real = R @Html.DisplayFor(model => model.RetornoReal)</p>

<h2>Definições </h2>
<p>Inflação: é um aumento geral nos preços de bens e serviços em uma economia.Resumindo, sabe aquele churrasco que ano passado você fazia com R$100,00, e hoje faz com R$120,00, esse aumento de preços é a inflação, que com a mesma quantidade de dinheiro de um período passado você consegue comprar menos. </p>
<p>Retorno bruto: Valor do seus investimentos antes do desconto imposto de renda retido na fonte no momento do resgate da sua aplicação</p>
<p>Retorno Liquido: Valor dos seus investimentos após o resgate e desconto do imposto de renda sobre o seu lucro.
Lembrando que o IR é regressivo, ou seja quanto mais tempo você deixar o seu dinheiro aplicado menos imposto ira pagar, e maior será o seu lucro. . </p>
<p>Até 180 dias (6 meses) = IR de 22,5% sobre o lucro</p>
<p>Até 181 dias até 360 dias (12 meses) = IR de 20,0% sobre o lucro</p>
<p>Até 361 dias até 720 dias (24 meses) = IR de 17,5% sobre o lucro</p>
<p>Acima de 720 dias (mais de 24 meses) = IR de 15,0% sobre o lucro</p>
<p>Retorno real: Valor liquido do seu investimento descontando a inflação do período da sua aplicação.Ou seja já descontado a desvalorização do seu dinheiro durante  </p>

<a asp-action="Index">Voltar</a>

 </body>   

Views/Taxa/Index.cshtml
@using System.Data

@{
    ViewData["Titele"] = "Calculadora de rentabilidade";
}

<html>
    <body>
        
    
<h1> Calculadora de rentabilidade para renda fixa</h1>
<h2>Objetivo</h2>
<p>Calcular o retorno real do seus investimentos em renda fixa pode ser um tarefa difícil, levando em conta o valor do imposto de renda sobre o seu lucro, e a inflação do período em que seu capital foi aplicado, para esse desafio desenvolvi essa calculadora para facilitar esse desafio, além disso aperfeiçoar e demostrar meus conhecimentos e .NetC#</p>

<h2>Calculadora</h2>
<p>Informe a taxa do seu investimento, o valor aplicado, e os meses da aplicação</p>
<div>
<form asp-controller="Taxa" asp-action="Calcular" method="get">
<select name="NomeTaxa" id="NomeTaxa">
    <option value= "CDI"> CDI </option>
    <option value= "Selic"> Selic </option>
    <option value= "IPCA"> IPCA </option>
</select>
    <input type="number" name="ValorInvestido" id="ValorInvestido" placeholder="Valor investido">
    <input type="number" name="Meses" id="Meses" placeholder="Meses investidos">
    <input type="submit" value="Calcular">
</form>
</div>

<h2>Taxas </h2>
<p>Taxa Selic: é a taxa básica de juros da economia. É o principal instrumento de política monetária utilizado pelo Banco Central do Brasil para controle da inflação</p>
<p>CDI: O CDI, ou Certificado de Depósito Interbancário, é uma taxa que determina o rendimento anual de diversos tipos de investimento</p>
<p>IPCA: Índice de preços no consumidor é usado para observar tendências de inflação. É calculado com base no preço médio necessário para comprar um conjunto de bens de consumo e serviços</p>

<h3>Nota</h3>
<p>Essa calculadora não se aplica para impostos isentos de IR como, letra de crédito imobiliário (LCI), letra de crédito do agronegócio (LCA) e poupança;
</p>

</body>
</html>
    